apiVersion: v1
kind: Service
metadata:
  name: app-k8s
  labels: 
    component: app-k8s
spec:
  selector:
    component: app-k8s
  type: NodePort  
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31082
